services:
  auth_postgres:
    image: postgres:15-alpine
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - shared_services
      - service_network

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8600:8000"
    env_file:
      - app/.env
    depends_on:
      - auth_postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:8000/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - shared_services
      - service_network

volumes:
  auth_postgres_data:

networks:
  shared_services:
    external: true
  service_network:
    external: true
