version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki-demo-loki-1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/tmp/loki-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/tmp/loki-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.4
    container_name: loki-demo-promtail-1
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - shared-logs:/app/logs
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    container_name: loki-demo-grafana-1
    ports:
      - "33000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  loki-data:
  grafana-data:
  shared-logs:
